# Window sizes
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 620

# Button sizes
MENU_BTN_WIDTH = 280
MENU_BTN_HEIGHT = 250
BACK_BTN_WIDTH = 100
CONTINUE_BTN_WIDTH = 150
CONFIRM_BTN_HEIGHT = 50
CANCEL_BTN_WIDTH = 120


# Spacing
MAIN_MARGIN = 50
SECTION_SPACING = 30
BUTTON_SPACING = 30
HEADER_SPACING = 20

# Seatmap
SEAT_WIDTH = 35
SEAT_HEIGHT = 28
SEAT_GRID_SPACING = 4
SEAT_LARGE_WIDTH = 55  # For SPC seats

SIDE_PANEL_WIDTH = 320

# icons
ICON_WIDTH = 80
ICON_HEIGHT = 80
